name: Build and publish NuGet package

on:
  push:
    branches:
    - "dev"

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create NuGet package
      run: dotnet pack -c Release -p:Version='${{ steps.gitversion.outputs.SemVer }}'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: bin/Release/
  Publish:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ${{ github.workspace}}/nuget
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet nuget push nugetPackage/*.nupkg --source https://nuget.pkg.github.com/WatchITProject/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
