name: Build and publish NuGet package

on:
  push:
    branches:
    - "dev"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create NuGet package
      run: dotnet pack --configuration Release --output ${{ github.workspace}}/nuget
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        path: ${{ github.workspace}}/nuget/*.nupkg
  Publish:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ${{ github.workspace}}/nuget
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: |
          foreach($file in (Get-ChildItem "./nuget" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --source https://nuget.pkg.github.com/WatchITProject/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          }
